# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='cicles',
            field=models.ManyToManyField(to='administrador.Ciclo', verbose_name='Ciclos'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='subjects',
            field=models.ManyToManyField(to='administrador.Materia', verbose_name='Materias'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='carrer',
            field=models.ManyToManyField(to='administrador.Carrera', verbose_name='Carreras'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
