# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20180803_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='status',
            field=models.CharField(choices=[('IN', 'Ingresado'), ('ET', 'En tr\xe1nsito'), ('CN', 'Cancelado'), ('AC', 'Acceptado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
    ]
