# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_historial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Periodo')),
                ('deleted', models.BooleanField(default=False)),
                ('carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Carrera', verbose_name='Carrera')),
            ],
        ),
    ]
