# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='carrer',
        ),
        migrations.AddField(
            model_name='periodo',
            name='carrer',
            field=models.ManyToManyField(to='administrador.Carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
