# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_auto_20180810_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='carrer',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='carrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Carrera', verbose_name='Carrera'),
        ),
    ]
