# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_auto_20180814_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='requirements',
            field=models.CharField(default=' ', max_length=256, verbose_name='Requerimientos'),
            preserve_default=False,
        ),
    ]
