# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_auto_20180807_0058'),
        ('alumno', '0002_remove_alumno_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('IN', 'Ingresado'), ('ET', 'En tr\xe1nsito'), ('CN', 'Cancelado'), ('AC', 'Acceptado')], default='IN', max_length=2, verbose_name='Estado')),
                ('description', models.CharField(max_length=256, verbose_name='Descripci\xf3n')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creaci\xf3n')),
                ('updated_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Actualizaci\xf3n')),
                ('reviewed_by', models.CharField(max_length=128, verbose_name='Revisado Por')),
                ('approved_by', models.CharField(max_length=128, verbose_name='Aprobado Por')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', verbose_name='Alumno')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proceso', verbose_name='Proceso')),
            ],
        ),
        migrations.AddField(
            model_name='historial',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.ProcesoAlumno', verbose_name='Proceso Alumno'),
        ),
    ]
