# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20180807_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAlumnoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Tema')),
                ('description', models.CharField(max_length=256, verbose_name='Descripci\xf3n')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Im\xe1gen')),
                ('deleted', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.ProcesoAlumno', verbose_name='Proceso')),
            ],
        ),
    ]
