# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_procesoalumnoitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoalumno',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Proceso', verbose_name='Proceso'),
        ),
    ]
