# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_auto_20180807_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoalumno',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Materia'),
        ),
    ]
