# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_auto_20180807_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoalumno',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creaci\xf3n'),
        ),
        migrations.AddField(
            model_name='procesoalumnoitems',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creaci\xf3n'),
        ),
    ]
