# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0010_auto_20180807_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='status',
        ),
        migrations.AddField(
            model_name='procesoalumno',
            name='status',
            field=models.CharField(choices=[('IN', 'Ingresado'), ('ET', 'En tr\xe1nsito'), ('CN', 'Cancelado'), ('AC', 'Acceptado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
    ]
