# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0011_auto_20180807_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoalumno',
            name='status',
            field=models.CharField(choices=[('IN', 'Ingresado'), ('ET', 'En tr\xe1nsito'), ('CN', 'Cancelado'), ('AC', 'Aceptado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
    ]
