# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_auto_20180813_0315'),
        ('alumno', '0012_auto_20180807_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='subjects',
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Carrera', verbose_name='Carrera'),
        ),
    ]
