# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0013_auto_20180813_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
