# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0014_alumno_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
