# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-14 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0015_alumno_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoalumnoitems',
            name='image',
        ),
        migrations.AddField(
            model_name='procesoalumno',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='procesoalumno',
            name='parcial',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Parcial'),
        ),
        migrations.AddField(
            model_name='procesoalumnoitems',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='procesoalumno',
            name='status',
            field=models.CharField(choices=[('IN', 'Ingresado'), ('ET', 'En tr\xe1nsito'), ('CN', 'Cancelado'), ('RC', 'Rechazado'), ('ER', 'En Revisi\xf3n'), ('FN', 'Finalizado'), ('AC', 'Aceptado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='procesoalumno',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Materia', verbose_name='Materia'),
        ),
    ]
