# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_auto_20180814_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoalumno',
            name='periodo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Periodo'),
        ),
    ]
