# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-14 04:14
from __future__ import unicode_literals

import alumno.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0017_procesoalumno_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoalumno',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[alumno.validators.validate_file_extension], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='procesoalumnoitems',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[alumno.validators.validate_file_extension], verbose_name='Documento'),
        ),
    ]
