# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0020_auto_20180814_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='approved_by',
        ),
    ]
