# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0021_remove_historial_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=256, verbose_name='Profesor')),
                ('nota', models.CharField(max_length=256, verbose_name='Nota')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descripci\xf3n')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creaci\xf3n')),
            ],
        ),
        migrations.AddField(
            model_name='procesoalumno',
            name='notes',
            field=models.ManyToManyField(to='alumno.Nota'),
        ),
    ]
