# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0023_auto_20180822_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoalumno',
            name='extras',
            field=models.CharField(blank=True, max_length=256, verbose_name='Correos Profesores Recalificaci\xf3n'),
        ),
    ]
