# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0026_auto_20180822_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoalumno',
            name='is_ok',
            field=models.BooleanField(default=False, verbose_name='Estudiante de acuerdo con su nota'),
        ),
        migrations.AlterField(
            model_name='procesoalumno',
            name='status',
            field=models.CharField(choices=[(b'IN', 'Ingresado'), (b'ER', 'En Revisi\xf3n'), (b'ET', 'En Tr\xe1nsito'), (b'CN', 'Cancelado'), (b'DR', 'Evaluaci\xf3n por Docentes Recalificadores'), (b'FN', 'Finalizado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
    ]
