# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0030_auto_20180822_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoalumno',
            name='status',
            field=models.CharField(choices=[(b'IN', 'Ingresado'), (b'ER', 'En Revisi\xf3n'), (b'ET', 'En Tr\xe1nsito'), (b'CN', 'Cancelado'), (b'ID', 'Ingreso nota por Docente'), (b'AE', 'Aceptado por Estudiante'), (b'RE', 'Rechazado por Estudiante'), (b'ED', 'Elecci\xf3n por Docentes Recalificadores'), (b'DR', 'Revisi\xf3n por Docentes Recalificadores'), (b'FN', 'Finalizado')], default='IN', max_length=2, verbose_name='Estado'),
        ),
    ]
