# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_auto_20180807_0852'),
        ('alumno', '0033_auto_20180823_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoalumno',
            name='extras',
        ),
        migrations.AddField(
            model_name='procesoalumno',
            name='extras',
            field=models.ManyToManyField(to='profesor.Profesor', verbose_name='Profesores Recalificaci\xf3n'),
        ),
    ]
